### ISSUE TITLE
Omar Kamal

### ISSUE THREAD

**Issue by invoqwer** [Latex4000/vinxis#1]
Omar Kamal

**Comment by cl8n** [comment]
This would cause an unacceptable amount of scope creep for this project, sorry.

**Comment by diodex00** [comment]
im a collaborator

**Comment by VINXIS** [comment]
Ermmmmm No

**Comment by invoqwer** [comment]
![image](https://github.com/user-attachments/assets/da22184a-05f3-4e52-9d3d-5e5c1220c722)
